account = "IUNIYXK-RFB39086.snowflakecomputing.com"
user = "SERVICE_ACCOUNT_USER"
role = "STREAMLIT_APP_ROLE"
warehouse = "SALES_INTELLIGENCE_WH"
database = "SALES_INTELLIGENCE"
schema = "DATA"

# Use the generated password from the CREATE USER statement above
password = "A_VERY_STRONG_UNIQUE_PASSWORD"